#include <stdio.h>
#include <string.h>
#include "object.h"
#include "move.h"
#include "toggle.h"
#include "onoff.h"
#include "combat.h"
#include "consumables.h"
#include "string_util.h"
#include "thief.h"
static const char *tags0[] = { "field", NULL};
static const char *tags1[] = { "cave", NULL};
static const char *tags2[] = { "south", "crack", NULL};
static const char *tags3[] = { "north", "crack", NULL};
static const char *tags4[] = { "east", "passage", NULL};
static const char *tags5[] = { "south", "passage", NULL};
static const char *tags6[] = { "west", "passage", NULL};
static const char *tags7[] = { "north", "passage", NULL};
static const char *tags8[] = { "south", "passage", NULL};
static const char *tags9[] = { "east", "passage", NULL};
static const char *tags10[] = { "north", "passage", NULL};
static const char *tags11[] = { "west", "passage", NULL};
static const char *tags12[] = { "cave", "passage", NULL};
static const char *tags13[] = { "cave", "passage", NULL};
static const char *tags14[] = { "cave", "passage", NULL};
static const char *tags15[] = { "cave", "passage", NULL};
static const char *customGet16(void)  { return moveObject(silver, player); }
static const char *tags16[] = { "silver", "coin", "silver coin", NULL};
static const char *tags17[] = { "gold", "coin", "gold coin", NULL};
static const char *customFight18(void)  { return "The guard merely raises an unamused eyebrow, and hardly notices your blows.\n"; }
static const char *customEat18(void)  { return "The guard looks alarmed as you open your jaw as wide as it will go, but unfortunately, it is not nearly wide enough to swallow the guard.\n"; }
static const char *update18(void)  { if (guard->location == field) { guard->location = cave; return "The guard paces into the cave.\n"; } else { guard->location = field; return "The guard paces into the field.\n"; } }
static const char *tags18[] = { "guard", "burly guard", NULL};
static const char *tags19[] = { "yourself", NULL};
static int condition20(void)  { return guard->health == 0 || silver->location == guard; }
static const char *tags20[] = { "east", "entrance", NULL};
static int condition21(void)  { return guard->health > 0 && silver->location != guard; }
static const char *tags21[] = { "east", "entrance", NULL};
static const char *tags22[] = { "west", "exit", NULL};
static const char *tags23[] = { "west", "north", "south", "forest", NULL};
static const char *tags24[] = { "east", "north", "rock", NULL};
static const char *tags25[] = { "backroom", NULL};
static const char *tags26[] = { "east", "west", "south", "rock", NULL};
static const char *close27(void)  { toggleReplace(openDoorToBackroom, closedDoorToBackroom); toggleReplace(openDoorToCave, closedDoorToCave); return "You close the door.\n"; }
static const char *tags27[] = { "south", "door", "doorway", NULL};
static const char *open28(void)  { toggleReplace(openDoorToBackroom, closedDoorToBackroom); toggleReplace(openDoorToCave, closedDoorToCave); return "You open the door.\n"; }
static const char *tags28[] = { "south", "door", "doorway", NULL};
static const char *close29(void)  { return (*openDoorToBackroom->close)(); }
static const char *tags29[] = { "north", "door", "doorway", NULL};
static const char *open30(void)  { return (*closedDoorToBackroom->open)(); }
static const char *tags30[] = { "north", "door", "doorway", NULL};
static const char *close31(void)  { toggleReplace(openBox, closedBox); return "You close the box.\n"; }
static const char *tags31[] = { "box", "wooden box", NULL};
static const char *open32(void)  { toggleReplace(openBox, closedBox); return "You open the box.\n"; }
static const char *lock32(void)  { toggleReplace(lockedBox, closedBox); return "You lock the box.\n"; }
static const char *tags32[] = { "box", "wooden box", NULL};
static const char *unlock33(void)  { toggleReplace(lockedBox, closedBox); return "You unlock the box.\n"; }
static const char *tags33[] = { "box", "wooden box", NULL};
static const char *tags34[] = { "key", "tiny key", NULL};
static const char *light35(void)  { return lampOff->turnOn(); }
static const char *turnOn35(void)  { toggleReplace(lampOn, lampOff); return "You turn on the lamp.\n"; }
static const char *tags35[] = { "lamp", NULL};
static const char *extinguish36(void)  { return lampOn->turnOff(); }
static const char *turnOff36(void)  { toggleReplace(lampOn, lampOff); return "You turn off the lamp.\n"; }
static const char *tags36[] = { "lamp", NULL};
static const char *tags37[] = { "thief", "robber", "scoundrel", NULL};

static int alwaysTrue(void) { return 1; }

OBJECT objs[] = {
	{	/* 0 = field */
		alwaysTrue,
		 "an open field",
		tags0,
		NULL,
		NULL,
		NULL,
		 "The field is a nice and quiet place under a clear blue sky.\n",
		"You see",
		"You can't get much closer than this.\n",
		99,
		 9999,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		 1,
		NULL
	},
	{	/* 1 = cave */
		alwaysTrue,
		 "a little cave",
		tags1,
		NULL,
		NULL,
		NULL,
		 "The cave is just a cold, damp, rocky chamber. There is a draft coming from somewhere.\n",
		"You see",
		"You can't get much closer than this.\n",
		99,
		 9999,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 2 = intoCaveMaze */
		alwaysTrue,
		 "a dark crack in the south wall",
		tags2,
		 cave,
		 caveMaze1,
		 caveMaze1,
		 "The crack looks large enough to crawl into.\n",
		"You see",
		 "You crawl into a narrow passage.\n",
		99,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "\0"
	},
	{	/* 3 = exitCaveMaze */
		alwaysTrue,
		 "a crack in the north wall",
		tags3,
		 caveMaze1,
		 cave,
		 cave,
		 "The crack looks large enough to crawl into.\n",
		"You see",
		 "You crawl out into the cave.\n",
		99,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 4 = fromCaveMaze1to2 */
		alwaysTrue,
		 "a passage",
		tags4,
		 caveMaze1,
		 caveMaze2,
		 caveMaze2,
		 "The passage leads east.\n",
		"You see",
		 "You crawl east.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "\0"
	},
	{	/* 5 = fromCaveMaze2to3 */
		alwaysTrue,
		 "a passage",
		tags5,
		 caveMaze2,
		 caveMaze3,
		 caveMaze3,
		 "The passage leads south.\n",
		"You see",
		 "You crawl south.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "\0"
	},
	{	/* 6 = fromCaveMaze3to4 */
		alwaysTrue,
		 "a passage",
		tags6,
		 caveMaze3,
		 caveMaze4,
		 caveMaze4,
		 "The passage leads west.\n",
		"You see",
		 "You crawl west.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "\0"
	},
	{	/* 7 = fromCaveMaze4to1 */
		alwaysTrue,
		 "a passage",
		tags7,
		 caveMaze4,
		 caveMaze1,
		 caveMaze1,
		 "The passage leads north.\n",
		"You see",
		 "You crawl north.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "\0"
	},
	{	/* 8 = fromCaveMaze1to4 */
		alwaysTrue,
		 "a passage",
		tags8,
		 caveMaze1,
		 caveMaze4,
		 caveMaze4,
		 "The passage leads south.\n",
		"You see",
		 "You crawl south.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "\0"
	},
	{	/* 9 = fromCaveMaze4to3 */
		alwaysTrue,
		 "a passage",
		tags9,
		 caveMaze4,
		 caveMaze3,
		 caveMaze3,
		 "The passage leads east.\n",
		"You see",
		 "You crawl east.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "\0"
	},
	{	/* 10 = fromCaveMaze3to2 */
		alwaysTrue,
		 "a passage",
		tags10,
		 caveMaze3,
		 caveMaze2,
		 caveMaze2,
		 "The passage leads north.\n",
		"You see",
		 "You crawl north.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "\0"
	},
	{	/* 11 = fromCaveMaze2to1 */
		alwaysTrue,
		 "a passage",
		tags11,
		 caveMaze2,
		 caveMaze1,
		 caveMaze1,
		 "The passage leads west.\n",
		"You see",
		 "You crawl west.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "\0"
	},
	{	/* 12 = caveMaze1 */
		alwaysTrue,
		 "a little cave",
		tags12,
		NULL,
		NULL,
		NULL,
		 "The cave is just a narrow, damp, passage, with barely any room to move.\nThe passage forks here, leading north, south, and east.\n",
		"You see",
		"You can't get much closer than this.\n",
		99,
		 9999,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 13 = caveMaze2 */
		alwaysTrue,
		 "a little cave",
		tags13,
		NULL,
		NULL,
		NULL,
		 "The cave is just a narrow, damp, passage, with barely any room to move.\nThe passage bends here, traveling south and west.\n",
		"You see",
		"You can't get much closer than this.\n",
		99,
		 9999,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 14 = caveMaze3 */
		alwaysTrue,
		 "a little cave",
		tags14,
		NULL,
		NULL,
		NULL,
		 "The cave is just a narrow, damp, passage, with barely any room to move.\nThe passage bends here, traveling north and west.\n",
		"You see",
		"You can't get much closer than this.\n",
		99,
		 9999,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 15 = caveMaze4 */
		alwaysTrue,
		 "a little cave",
		tags15,
		NULL,
		NULL,
		NULL,
		 "The cave is just a narrow, damp, passage, with barely any room to move.\nThe passage bends here, traveling north and east.\n",
		"You see",
		"You can't get much closer than this.\n",
		99,
		 9999,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 16 = silver */
		alwaysTrue,
		 "a silver coin",
		tags16,
		 field,
		NULL,
		NULL,
		 "The coin has an eagle on the obverse.\n",
		"You see",
		"You can't get much closer than this.\n",
		 1,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		customGet16,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "A silver coin glistens on the ground among the leaves."
	},
	{	/* 17 = gold */
		alwaysTrue,
		 "a gold coin",
		tags17,
		 openBox,
		NULL,
		NULL,
		 "The shiny coin seems to be a rare and priceless artifact.\n",
		"You see",
		"You can't get much closer than this.\n",
		 1,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 18 = guard */
		alwaysTrue,
		 "a burly guard",
		tags18,
		 field,
		NULL,
		NULL,
		 "The guard is a really big fellow.\n",
		 "He has",
		"You can't get much closer than this.\n",
		99,
		 20,
		 100,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		customFight18,
		NULL,
		customEat18,
		NULL,
		update18,
		0,
		NULL
	},
	{	/* 19 = player */
		alwaysTrue,
		 "yourself",
		tags19,
		 field,
		NULL,
		NULL,
		 "You would need a mirror to look at yourself.\n",
		 "You have",
		"You can't get much closer than this.\n",
		99,
		 20,
		 100,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 20 = intoCave */
		condition20,
		 "a cave entrance to the east",
		tags20,
		 field,
		 cave,
		 cave,
		 "The entrance is just a narrow opening in a small outcrop.\n",
		"You see",
		 "You walk into the cave.\n",
		99,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "\0"
	},
	{	/* 21 = intoCaveBlocked */
		condition21,
		 "a cave entrance to the east",
		tags21,
		 field,
		NULL,
		 cave,
		 "The entrance is just a narrow opening in a small outcrop.\n",
		"You see",
		 "The guard stops you from walking into the cave.\n",
		99,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "\0"
	},
	{	/* 22 = exitCave */
		alwaysTrue,
		 "an exit to the west",
		tags22,
		 cave,
		 field,
		 field,
		 "Sunlight pours in through an opening in the cave's wall.\n",
		"You see",
		 "You walk out of the cave.\n",
		99,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "There is sunlight coming from the west."
	},
	{	/* 23 = wallField */
		alwaysTrue,
		 "dense forest all around",
		tags23,
		 field,
		NULL,
		NULL,
		 "The field is surrounded by trees and undergrowth.\n",
		"You see",
		 "Dense forest is blocking the way.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "There is a cave entrance in the rock wall to the east, and dense forest on all other sides."
	},
	{	/* 24 = wallCave */
		alwaysTrue,
		 "solid rock all around",
		tags24,
		 cave,
		NULL,
		NULL,
		 "There is a crack in the southern wall.\n",
		"You see",
		 "Solid rock is blocking the way.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "You are surrounded on all sides by solid rock."
	},
	{	/* 25 = backroom */
		alwaysTrue,
		 "a backroom",
		tags25,
		NULL,
		NULL,
		NULL,
		 "The room is dusty and messy.\n",
		"You see",
		"You can't get much closer than this.\n",
		99,
		 9999,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 26 = wallBackroom */
		alwaysTrue,
		 "solid rock all around",
		tags26,
		 backroom,
		NULL,
		NULL,
		 "Trendy wallpaper covers the rock walls.\n",
		"You see",
		 "Solid rock is blocking the way.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "This appears to be only one exit."
	},
	{	/* 27 = openDoorToBackroom */
		alwaysTrue,
		 "an open door to the south",
		tags27,
		NULL,
		 backroom,
		 backroom,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into a backroom.\n",
		99,
		0,
		0,
		 isAlreadyOpen,
		close27,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "There is an open door leading into some sort of backroom to the south."
	},
	{	/* 28 = closedDoorToBackroom */
		alwaysTrue,
		 "a closed door to the south",
		tags28,
		 caveMaze3,
		NULL,
		 backroom,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		0,
		0,
		open28,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "There is a closed door to the south."
	},
	{	/* 29 = openDoorToCave */
		alwaysTrue,
		 "an open door to the north",
		tags29,
		NULL,
		 caveMaze3,
		 caveMaze3,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into a backroom.\n",
		99,
		0,
		0,
		 isAlreadyOpen,
		close29,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "There is an open door leading into a cave to your north."
	},
	{	/* 30 = closedDoorToCave */
		alwaysTrue,
		 "an closed door to the north",
		tags30,
		 backroom,
		NULL,
		 caveMaze3,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		0,
		0,
		open30,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "There is a closed door in the north wall."
	},
	{	/* 31 = openBox */
		alwaysTrue,
		 "a wooden box",
		tags31,
		NULL,
		NULL,
		NULL,
		 "The box is open.\n",
		"You see",
		"You can't get much closer than this.\n",
		 5,
		 10,
		0,
		 isAlreadyOpen,
		close31,
		 isStillOpen,
		 isAlreadyOpen,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 32 = closedBox */
		alwaysTrue,
		 "a wooden box",
		tags32,
		NULL,
		NULL,
		NULL,
		 "The box is closed.\n",
		"You see",
		"You can't get much closer than this.\n",
		 5,
		0,
		0,
		open32,
		 isAlreadyClosed,
		lock32,
		 isAlreadyUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 33 = lockedBox */
		alwaysTrue,
		 "a wooden box",
		tags33,
		 backroom,
		NULL,
		NULL,
		 "The box is closed.\n",
		"You see",
		"You can't get much closer than this.\n",
		 5,
		0,
		0,
		 isStillLocked,
		 isAlreadyClosed,
		 isAlreadyLocked,
		unlock33,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 34 = keyForBox */
		alwaysTrue,
		 "a tiny key",
		tags34,
		 cave,
		NULL,
		NULL,
		 "The key is really small and shiny.\n",
		"You see",
		"You can't get much closer than this.\n",
		 1,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 35 = lampOff */
		alwaysTrue,
		 "a lamp",
		tags35,
		 field,
		NULL,
		NULL,
		 "The lamp is off.\n",
		"You see",
		"You can't get much closer than this.\n",
		 5,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		turnOn35,
		 isAlreadyOff,
		light35,
		 isAlreadyExtinguished,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 36 = lampOn */
		alwaysTrue,
		 "a lamp",
		tags36,
		NULL,
		NULL,
		NULL,
		 "The lamp is on.\n",
		"You see",
		"You can't get much closer than this.\n",
		 5,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		 isAlreadyOn,
		turnOff36,
		 isAlreadyLit,
		extinguish36,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		 1,
		NULL
	},
	{	/* 37 = thief */
		alwaysTrue,
		 "a sneaky thief",
		tags37,
		 caveMaze1,
		NULL,
		NULL,
		 "The thief is prowling the corridors looking for something to steal.",
		"You see",
		"You can't get much closer than this.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		 thiefUpdate,
		0,
		NULL
	}
};
