#include <stdio.h>
#include <string.h>
#include "object.h"
#include "move.h"
#include "toggle.h"
#include "onoff.h"
#include "combat.h"
#include "consumables.h"
#include "string_util.h"
static const char *tags0[] = { "yourself", NULL};
static const char *tags1[] = { "deku tree", "deku", "tree", "lobby", "main hall", "main", NULL};
static const char *tags2[] = { "lobby", "main hall", "upper level", NULL};
static const char *tags3[] = { "lobby", "main hall", "upper level", NULL};
static const char *tags4[] = { "pool", "basement", NULL};
static const char *tags5[] = { "up", "ladder", NULL};
static const char *tags6[] = { "down", "ledge", "edge", NULL};
static const char *tags7[] = { "up", "ladder", "vines", NULL};
static const char *tags8[] = { "down", "ladder", NULL};
static int condition9(void)  { return deku_webPitLobby->location == deku_lobby; }
static const char *tags9[] = { "ledge", "edge", "middle", "center", "centre", "bottom", NULL};
static int condition10(void)  { return deku_weblessPitLobby->location == deku_lobby; }
static const char *tags10[] = { "down", "ledge", "edge", "middle", "center", "centre", "bottom", NULL};
static const char *tags11[] = { "up", "ladder", "vines", NULL};
static const char *open12(void)  {return "The web is too strong to tear with your hands.\n";}
static const char *update12(void)  { if (deku_webPitLobby->location == deku_lobby){if (player->location == deku_basementPool){ toggleReplace(deku_webPitLobby, deku_weblessPitLobby);}} return "";}
static const char *tags12[] = { "down", "pit", "web", NULL};
static const char *tags13[] = { "down", "pit", "web", NULL};
static const char *tags14[] = { "west", "north", "east", "wall", "walls", NULL};

static int alwaysTrue(void) { return 1; }

OBJECT objs[] = {
	{	/* 0 = player */
		alwaysTrue,
		 "yourself",
		tags0,
		 deku_lobby,
		NULL,
		NULL,
		 "As far as you can see, you look like any regular little boy in a bright green tunic.\n",
		 "You have",
		"You can't get much closer than this.\n",
		99,
		 20,
		 100,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		 1,
		NULL
	},
	{	/* 1 = deku_lobby */
		alwaysTrue,
		 "Deku tree lobby",
		tags1,
		NULL,
		NULL,
		NULL,
		 "The inside of the Deku tree is hollowed into an irregular round chamber, going up several floors.\n",
		"You see",
		"You can't get much closer than this.\n",
		99,
		 9999,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 2 = deku_level2 */
		alwaysTrue,
		 "above Deku tree lobby",
		tags2,
		NULL,
		NULL,
		NULL,
		 "This level of the Deku tree's main hall consists of sloping ledges winding around the walls of the chamber.\n",
		"You see",
		"You can't get much closer than this.\n",
		99,
		 9999,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 3 = deku_level3 */
		alwaysTrue,
		 "high above Deku tree lobby",
		tags3,
		NULL,
		NULL,
		NULL,
		 "The top floor of the main hall is made up wooden plank walkways between four protruding wooden platforms.\n",
		"You see",
		"You can't get much closer than this.\n",
		99,
		 9999,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 4 = deku_basementPool */
		alwaysTrue,
		 "the Deku tree's basement pool",
		tags4,
		NULL,
		NULL,
		NULL,
		 "The top floor of the main hall is made up wooden plank walkways between four protruding wooden platforms.\n",
		"You see",
		"You can't get much closer than this.\n",
		99,
		 9999,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 5 = deku_lobbyLadder */
		alwaysTrue,
		 "a ladder against the wall",
		tags5,
		 deku_lobby,
		 deku_level2,
		 deku_level2,
		 "The ladder is more of a tangle of dried vines and branches, leading upward onto a ledge on the second floor.\n",
		"You see",
		 "You climb the ladder onto the ledge above.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 6 = deku_downFrom2ndFloor */
		alwaysTrue,
		 "the edge of the walkway",
		tags6,
		 deku_level2,
		 deku_lobby,
		 deku_lobby,
		 "The edge of this floor sharply drops off to the first floor a short distance below.\n",
		"You see",
		 "You throw caution to the wind and leap off the ledge onto the floor below. Luckily, you land solidly on your feet.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 7 = deku_2ndLadder */
		alwaysTrue,
		 "a ladder against the wall",
		tags7,
		 deku_level2,
		 deku_level3,
		 deku_level3,
		 "The ladder is more of a tangle of dried vines and branches, leading upward onto a ledge on the top floor.\n",
		"You see",
		 "You climb the ladder onto the ledge above.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 8 = deku_downToSecondFloor */
		alwaysTrue,
		 "a vine ladder against the outer wall",
		tags8,
		 deku_level3,
		 deku_level2,
		 deku_level2,
		 "The ladder from the floor beneath continues on the wall on this floor, ending at the ceiling directly above you.\n",
		"You see",
		 "You climb back down the ladder onto the ledge below.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 9 = deku_jumpFromTopWeb */
		condition9,
		 "ledges reaching towards the middle of the room",
		tags9,
		 deku_level3,
		 deku_basementPool,
		 deku_lobby,
		 "The edge of this floor sharply drops off to the first floor a short distance below.\n",
		"You see",
		 "You dive gracefully off the protruding edge and smack face-first into the web covering the pit below. The web stretches alarmingly, and just when it it about to recoil and send you likely careening into the ceiling, the surface snaps, and you go tumbling ungracefully down the chute and into the ice-cold water far below with a shock.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 10 = deku_jumpFromTop */
		condition10,
		 " ",
		tags10,
		 deku_level3,
		 deku_basementPool,
		 deku_basementPool,
		 "The edge of this floor sharply drops off to the first floor a short distance below.\n",
		"You see",
		 "You throw caution to the wind and leap off the ledge onto the floor below. Luckily, you land solidly on your feet.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		 "\0"
	},
	{	/* 11 = deku_basementLadder */
		alwaysTrue,
		 "a tangle of vines up the east wall",
		tags11,
		 deku_basementPool,
		 deku_lobby,
		 deku_lobby,
		 "The ladder is more of a tangle of dried vines and branches, leading up the chute above.\n",
		"You see",
		 "You climb back up the chute.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 12 = deku_webPitLobby */
		alwaysTrue,
		 "a web-covered pit",
		tags12,
		 deku_lobby,
		NULL,
		 deku_basementPool,
		 "The pit is covered by a thick, elastic layer of web. You can see water at the bottom of a circular shaft.\n",
		"You see",
		 "You stand on the web, but that's as far as you go.\n",
		99,
		0,
		0,
		open12,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		update12,
		0,
		NULL
	},
	{	/* 13 = deku_weblessPitLobby */
		alwaysTrue,
		 "a gaping pit",
		tags13,
		NULL,
		 deku_basementPool,
		 deku_basementPool,
		 "The web is gone from the pit. You can see water at the bottom of a circular shaft.\n",
		"You see",
		 "You leap into the pit and plummet a long way, hitting the deep water at the bottom with a shock.\n",
		99,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	},
	{	/* 14 = deku_wallLobby */
		alwaysTrue,
		 "living wood surrounding you",
		tags14,
		 deku_lobby,
		NULL,
		NULL,
		 "The Deku tree is growing all around you. You can feel the life coursing through these living walls, but you also sense something terribly wrong eating away deep within.\n",
		"You see",
		 "You can't walk through the wood of the tree.\n",
		99,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		cannotTurnOn,
		cannotTurnOff,
		cannotLight,
		cannotExtinguish,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		0,
		NULL
	}
};
